services:
    oportunidade.repository:
        class: infraestrutura\Persistence\Doctrine\OportunidadeRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Domain\Model\Oportunidade
